name: 'Translate i18next Files'
description: 'Translate i18next JSON files using AI and create a pull request with the changes'

inputs:
  sourcePattern:
    description: 'Glob pattern for source language file(s)'
    required: true
  sourceLanguage:
    description: 'Source language code'
    required: true
    default: 'en'
  targetLanguages:
    description: 'Comma-separated list of target language codes'
    required: true
  outputPattern:
    description: 'Output file pattern (e.g., "locales/<lang>.json")'
    required: true
  replaceAll:
    description: 'Replace all existing translations'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Run translation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        npx i18next-translate \
          --source "${{ inputs.sourcePattern }}" \
          --source-lang "${{ inputs.sourceLanguage }}" \
          --target ${{ inputs.targetLanguages }} \
          --output "${{ inputs.outputPattern }}" \
          ${{ inputs.replaceAll == 'true' && '--replace-all' || '' }}
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: 'chore: update translations'
        title: 'Update translations'
        body: |
          This PR updates translations for i18next JSON files.

          Source pattern: ${{ inputs.sourcePattern }}
          Source language: ${{ inputs.sourceLanguage }}
          Target languages: ${{ inputs.targetLanguages }}
          Output pattern: ${{ inputs.outputPattern }}
          Replace all: ${{ inputs.replaceAll }}
        branch: update-translations
        delete-branch: true
